export default {
  CREATING: 'CREATING',
  CREATE_ERROR: 'CREATE_ERROR',
  CREATE_SUCCESS: 'CREATE_SUCCESS',
  FETCH_SINGLE_SUCCESS: 'FETCH_SINGLE_SUCCESS',
  FETCH_SINGLE_ERROR: 'FETCH_SINGLE_ERROR',
  FETCHING_SINGLE: 'FETCHING_SINGLE',
};
