export default {
  CREATING: 'CREATING',
  CREATE_ERROR: 'CREATE_ERROR',
  CREATE_SUCCESS: 'CREATE_SUCCESS',
  FETCH_SINGLE_SUCCESS: 'FETCH_SINGLE_SUCCESS',
  FETCH_SINGLE_ERROR: 'FETCH_SINGLE_ERROR',
  FETCHING_SINGLE: 'FETCHING_SINGLE',
  FETCHING_ARTICLE: 'FETCHING_ARTICLE',
  FETCH_ARTICLE_ERROR: 'FETCH_ARTICLE_ERROR',
  FETCH_ARTICLE_SUCCESS: 'FETCH_ARTICLE_SUCCESS',
  HIGHLIGHT_UPLOAD_SUCCESS: 'HIGHLIGHT_UPLOAD_SUCCESS',
  HIGHLIGHT_UPLOADING: 'HIGHLIGHT_UPLOADING',
  HIGHLIGHT_UPLOAD_FAILED: 'HIGHLIGHT_UPLOAD_FAILED',
};
