export default {
  CREATING: 'CREATING',
  CREATE_ERROR: 'CREATE_ERROR',
  CREATE_SUCCESS: 'CREATE_SUCCESS',
  FETCHING_ARTICLE: 'FETCHING_ARTICLE',
  FETCH_ARTICLE_ERROR: 'FETCH_ARTICLE_ERROR',
  FETCH_ARTICLE_SUCCESS: 'FETCH_ARTICLE_SUCCESS',
};
