const SET_CREATE_STATUS = 'SET_CREATE_STATUS';
const SET_SINGLE_FETCH_STATUS = 'SET_SINGLE_FETCH_STATUS';
const SET_FETCH_ARTICLE_STATE = 'SET_FETCH_ARTICLE_STATE';
const SET_FETCH_ARTICLE_ERROR = 'SET_FETCH_ARTICLE_ERROR';
const SET_ARTICLE_CATEGORY = 'SET_ARTICLE_CATEGORY';
const ADD_ARTICLE_DATA = 'ADD_ARTICLE_DATA';
const ADD_NEWLY_CREATED_ARTICLE = 'ADD_NEWLY_CREATED_ARTICLE';
const UPDATE_CATEGORY_DATA = 'UPDATE_CATEGORY_DATA';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const SET_BOOKMARK_ARTICLE_STATE = 'SET_BOOKMARK_ARTICLE_STATE';
const SET_BOOKMARK_ARTICLE_ERROR = 'SET_BOOKMARK_ARTICLE_ERROR';
const SET_REMOVE_BOOKMARK_STATE = 'SET_REMOVE_BOOKMARK_STATE';
const SET_REMOVE_BOOKMARK_ERROR = 'SET_REMOVE_BOOKMARK_ERROR';

export default {
  SET_CREATE_STATUS,
  SET_FETCH_ARTICLE_STATE,
  SET_FETCH_ARTICLE_ERROR,
  SET_ARTICLE_CATEGORY,
  ADD_ARTICLE_DATA,
  UPDATE_CATEGORY_DATA,
  SET_CURRENT_PAGE,
  SET_SINGLE_FETCH_STATUS,
  SET_BOOKMARK_ARTICLE_STATE,
  SET_BOOKMARK_ARTICLE_ERROR,
  SET_REMOVE_BOOKMARK_STATE,
  SET_REMOVE_BOOKMARK_ERROR,
  ADD_NEWLY_CREATED_ARTICLE,
};
