const SET_CREATE_STATUS = 'SET_CREATE_STATUS';
const SET_FETCH_ARTICLE_STATE = 'SET_FETCH_ARTICLE_STATE';
const SET_FETCH_ARTICLE_ERROR = 'SET_FETCH_ARTICLE_ERROR';
const SET_ARTICLE_CATEGORY = 'SET_ARTICLE_CATEGORY';
const ADD_ARTICLE_DATA = 'ADD_ARTICLE_DATA';

export default {
  SET_CREATE_STATUS,
  SET_FETCH_ARTICLE_STATE,
  SET_FETCH_ARTICLE_ERROR,
  SET_ARTICLE_CATEGORY,
  ADD_ARTICLE_DATA,
};
