export default {
  LOGGING_IN: 'LOGGING_IN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGGING_FACEBBOK: 'LOGGING_FACEBBOK',
  LOGGING_FACEBBOK_ERROR: 'LOGGING_FACEBBOK_ERROR',
  LOGGING_FACEBBOK_SUCCESS: 'LOGGING_FACEBBOK_SUCCESS',
};
