export { default as cancel } from './cancel.svg'
export { default as email } from './email.svg'
export { default as facebook } from './facebook.svg'
export { default as google } from './google.svg'
export { default as key } from './key.svg'
export { default as lock } from './lock.svg'
export { default as twitter } from './twitter.svg'
