const SET_FETCH_ARTICLE_STATE = 'SET_FETCH_ARTICLE_STATE';
const SET_FETCH_ARTICLE_ERROR = 'SET_FETCH_ARTICLE_ERROR';
const ADD_ARTICLE_DATA = 'ADD_ARTICLE_DATA';

export default {
  SET_FETCH_ARTICLE_STATE,
  SET_FETCH_ARTICLE_ERROR,
  ADD_ARTICLE_DATA,
};
