export default {
  PICTURE_UPDATING: 'PICTURE UPDATING',
  UPDATE_SUCCESS: 'UPDATE SUCCESSFUL',
  UPDATE_ERROR: 'UPDATE ERROR',
  PROFILE_UPDATING: 'PROFILE_UPDATING',
  PROFILE_UPDATE_SUCCESS: 'PROFILE_SUCCESS',
  PROFILE_UPDATE_ERROR: 'PROFILE_UPDATE_ERROR',
};
