const SET_USER_PROFILE = 'SET_USER_PROFILE';
const VIEW_USER_PROFILE = 'VIEW_USER_PROFILE';
const SET_ERROR_STATUS = 'SET_ERROR_STATUS';
const SET_UPLOADING_STATUS = 'SET_UPLOADING_STATUS';
const SET_PICTURE_UPLOADED = 'SET_PICTURE_UPLOADED';
const SET_PROFILE_UPDATE = 'SET_PROFILE_UPDATE';
export default {
  SET_USER_PROFILE,
  VIEW_USER_PROFILE,
  SET_ERROR_STATUS,
  SET_UPLOADING_STATUS,
  SET_PICTURE_UPLOADED,
  SET_PROFILE_UPDATE,
};
