const SET_UPDATE_PASSWORD_STATE = 'SET_UPDATE_PASSWORD_STATE';
const SET_UPDATE_PASSWORD_ERROR = 'SET_UPDATE_PASSWORD_ERROR';

export default { SET_UPDATE_PASSWORD_STATE, SET_UPDATE_PASSWORD_ERROR };
